### ISSUE TITLE
Using wildfly-extras/creaper library

### ISSUE THREAD

**Issue by osmman** [jboss-soa-qa/jcontainer-manager#74]
Should we use [wildfly-extras/creaper](https://github.com/wildfly-extras/creaper) library for managing Wildfly an EAP servers?

**Comment by basovnik** [comment]
I am in! But there is one issue connected witch batch commands. It must me fixed before we can use it.
https://github.com/wildfly-extras/creaper/issues/54

**Comment by basovnik** [comment]
Creaper project does not have implicit support for all the CLI commands. They have to implement special classes for each command.

https://github.com/wildfly-extras/creaper/tree/master/commands/src/main/java/org/wildfly/extras/creaper/commands

**Comment by Ladicek** [comment]
That's not true, strictly speaking. As I mentioned in wildfly-extras/creaper#54, there's `OnlineManagementClient.executeCli` and `CliFile`. It's true we usually prefer to avoid CLI, but we're by no means strict about it and some commands are indeed implemented using CLI operations.

**Comment by basovnik** [comment]
@Ladicek Great. I am sorry, I did not notice method `OnlineManagementClient.executeCli`. Is it somehow possible to get result of this method? We were using the following workaround:

**Comment by Ladicek** [comment]
Oh well. That's the difference between `execute(String)`, which returns a result, and `executeCli(String)`, which doesn't return a result but supports "local operations" (like `if` or `batch`).

There's currently no such thing as your hack in Creaper. Not sure how easy or hard it would be to define such feature meaningfully.
